version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recomendacao_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mapeia o diretório de trabalho para o contêiner
    command: uvicorn src.webapp.app:app --host 0.0.0.0 --port 8000
