services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recomendacao_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src

docker compose -f docker-compose.yml run --rm api uvicorn src.webapp.app:app --host 0.0.0.0 --port 8000
