services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recomendacao_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
